version: "3.9"
services:
  web:
    image: eufy_kinesis_rtsp:v1
    ports:
      - "5000:5000"
    environment:
      - ROOM_NAME
    env_file:
      - ${ROOM_NAME}.env
    command: [ "python3", "camera.py" ]
