version: "3.9"
services:
  nursery:
    image: eufy_kinesis_rtsp:v1
    ports:
      - "5000:5000"
    env_file:
      - nursery.env
    command: [ "python3", "camera.py" ]
  living_room:
    image: eufy_kinesis_rtsp:v1
    ports:
      - "5001:5001"
    env_file:
      - living_room.env
    command: [ "python3", "camera.py" ]
